//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakipWeb.Areas.MusteriCalisan.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcilanCagri
    {
        public int ID { get; set; }
        public int CagriNo { get; set; }
        public string YetkiliKisi { get; set; }
        public string Gsm { get; set; }
        public string Email { get; set; }
        public string CihazTipi { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string SeriNo { get; set; }
        public string BarkodNo { get; set; }
        public System.DateTime AcilisTarihi { get; set; }
        public string Aciklama { get; set; }
        public string CagriDetayi { get; set; }
        public bool IslemGorduMu { get; set; }
        public string SarfMalzemeTalebi { get; set; }
        public int McID { get; set; }
    }
}
