//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakipWeb.Areas.MusteriYonetici.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketYapma
    {
        public int ID { get; set; }
        public int AnketID { get; set; }
        public int TamamlananCagriID { get; set; }
        public int MyID { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Anket Anket { get; set; }
    }
}
