//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakipWeb.Areas.Firma.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaYonetici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FirmaYonetici()
        {
            this.FirmaCalisani = new HashSet<FirmaCalisani>();
            this.SozlesmeYapma = new HashSet<SozlesmeYapma>();
        }
    
        public int FyID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Gsm { get; set; }
        public string Email { get; set; }
        public int FirmaID { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Firma Firma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmaCalisani> FirmaCalisani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SozlesmeYapma> SozlesmeYapma { get; set; }
    }
}
