//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakipWeb.Areas.Firma.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sozlesme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sozlesme()
        {
            this.SozlesmeYapma = new HashSet<SozlesmeYapma>();
        }
    
        public int ID { get; set; }
        public string SozlesmeAdi { get; set; }
        public decimal AnlasmaUcreti { get; set; }
        public int SlaSuresi { get; set; }
        public System.DateTime BaslangicTarih { get; set; }
        public System.DateTime BitisTarih { get; set; }
        public int ParcaDahilMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SozlesmeYapma> SozlesmeYapma { get; set; }
    }
}
