//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakipWeb.Areas.FirmaYonetici.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtananCagrilar
    {
        public int ID { get; set; }
        public int AtananID { get; set; }
        public int AtayanID { get; set; }
        public System.DateTime VarisTarih { get; set; }
        public Nullable<bool> Aciliyet { get; set; }
        public string YoneticiNotu { get; set; }
        public int CagriNo { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual FirmaCalisani FirmaCalisani { get; set; }
        public virtual FirmaYonetici FirmaYonetici { get; set; }
    }
}
