//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakipWeb.Areas.FirmaYonetici.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CihazBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CihazBilgileri()
        {
            this.TamamlananCagrilar = new HashSet<TamamlananCagrilar>();
            this.TamamlananCagrilar1 = new HashSet<TamamlananCagrilar>();
            this.TamamlananCagrilar2 = new HashSet<TamamlananCagrilar>();
            this.TamamlananCagrilar3 = new HashSet<TamamlananCagrilar>();
        }
    
        public int CihazID { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string SeriNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TamamlananCagrilar> TamamlananCagrilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TamamlananCagrilar> TamamlananCagrilar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TamamlananCagrilar> TamamlananCagrilar2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TamamlananCagrilar> TamamlananCagrilar3 { get; set; }
    }
}
