//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakipWeb.Areas.FirmaYonetici.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriYonetici
    {
        public int MyID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Email { get; set; }
        public string Gsm { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int MusteriID { get; set; }
    
        public virtual Musteri Musteri { get; set; }
    }
}
