//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakipWeb.Areas.FirmaYonetici.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SozlesmeYapma
    {
        public int SozlesmeID { get; set; }
        public int FyID { get; set; }
        public int MID { get; set; }
    
        public virtual FirmaYonetici FirmaYonetici { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual Sozlesme Sozlesme { get; set; }
    }
}
